// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcwCW8faufR9Z3gtGd6zT9S2echJgY2Hc',
    appId: '1:605351102825:web:cf882d4d099b461e2c15f8',
    messagingSenderId: '605351102825',
    projectId: 'clubhub-ed76f',
    authDomain: 'clubhub-ed76f.firebaseapp.com',
    storageBucket: 'clubhub-ed76f.appspot.com',
    measurementId: 'G-M6398ZZP7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5WACKXNMV_lkEm_jv2C7JN31D6Tj38GU',
    appId: '1:605351102825:android:0cd2f51b3d7000ae2c15f8',
    messagingSenderId: '605351102825',
    projectId: 'clubhub-ed76f',
    storageBucket: 'clubhub-ed76f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4bfWRCsLvuyYZvbvRVBp7oAMZMNawp24',
    appId: '1:605351102825:ios:72ffa416066e47e82c15f8',
    messagingSenderId: '605351102825',
    projectId: 'clubhub-ed76f',
    storageBucket: 'clubhub-ed76f.appspot.com',
    iosBundleId: 'com.example.clubHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4bfWRCsLvuyYZvbvRVBp7oAMZMNawp24',
    appId: '1:605351102825:ios:1b6c4d8b58f3b1222c15f8',
    messagingSenderId: '605351102825',
    projectId: 'clubhub-ed76f',
    storageBucket: 'clubhub-ed76f.appspot.com',
    iosBundleId: 'com.example.clubHub.RunnerTests',
  );
}
